"""fix(users) : created_at, updated_at, and password attribute

Revision ID: 79020c897a8c
Revises: 7baa19a055a9
Create Date: 2025-04-06 22:31:18.977075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79020c897a8c'
down_revision = '7baa19a055a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'USER', 'STAFF', name='roleenum'), nullable=False),
    sa.Column('name_lengkap', sa.String(length=30), nullable=False),
    sa.Column('tanggal_lahir', sa.DateTime(), nullable=False),
    sa.Column('email', sa.String(length=35), nullable=False),
    sa.Column('no_telepon', sa.String(length=13), nullable=False),
    sa.Column('jenis_kelamin', sa.Enum('MALE', 'FEMALE', 'OTHER', name='genderenum'), nullable=False),
    sa.Column('username', sa.String(length=15), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_user'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('User')
    # ### end Alembic commands ###
