"""fix(users) : created_at, updated_at, and password attribute

Revision ID: 7baa19a055a9
Revises: 83cf676c23d8
Create Date: 2025-04-06 22:21:11.951161

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7baa19a055a9'
down_revision = '83cf676c23d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'USER', 'STAFF', name='roleenum'), nullable=False),
    sa.Column('name_lengkap', sa.String(length=30), nullable=False),
    sa.Column('tanggal_lahir', sa.DateTime(), nullable=False),
    sa.Column('email', sa.String(length=35), nullable=False),
    sa.Column('no_telepon', sa.String(length=13), nullable=False),
    sa.Column('jenis_kelamin', sa.Enum('MALE', 'FEMALE', 'OTHER', name='genderenum'), nullable=False),
    sa.Column('username', sa.String(length=15), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_user'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('email')

    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id_user', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('role', mysql.ENUM('ADMIN', 'USER', 'STAFF'), nullable=False),
    sa.Column('name_lengkap', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('tanggal_lahir', mysql.DATETIME(), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=35), nullable=False),
    sa.Column('no_telepon', mysql.VARCHAR(length=13), nullable=False),
    sa.Column('jenis_kelamin', mysql.ENUM('MALE', 'FEMALE', 'OTHER'), nullable=False),
    sa.Column('username', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=25), nullable=False),
    sa.PrimaryKeyConstraint('id_user'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('email', ['email'], unique=True)

    op.drop_table('User')
    # ### end Alembic commands ###
