"""fix(user_model) : added nama_instansi and deleted no_telepon

Revision ID: 7f06b0a966dc
Revises: bc9ebe34d39a
Create Date: 2025-05-24 21:47:11.317436

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7f06b0a966dc'
down_revision = 'bc9ebe34d39a'
branch_labels = None
depends_on = None


def upgrade():
    op.add_column('User', sa.Column('nama_instansi', sa.String(length=100), nullable=True))
    op.drop_column('User', 'no_telepon')

def downgrade():
    op.add_column('User', sa.Column('no_telepon', sa.String(length=13), nullable=False))
    op.drop_column('User', 'nama_instansi')
    
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pengaduan', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('pengaduan_ibfk_1', 'user', ['id_user'], ['id_user'])

    with op.batch_alter_table('laporan', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('laporan_ibfk_1', 'user', ['id_user'], ['id_user'])

    op.create_table('user',
    sa.Column('id_user', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('role', mysql.ENUM('ADMIN', 'USER', 'STAFF'), nullable=False),
    sa.Column('name_lengkap', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=35), nullable=False),
    sa.Column('no_telepon', mysql.VARCHAR(length=13), nullable=False),
    sa.Column('username', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id_user'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('email', ['email'], unique=True)

    op.drop_table('User')
    # ### end Alembic commands ###
