"""added table laporan

Revision ID: 81628ce16a9e
Revises: 3ba718bf39af
Create Date: 2025-05-20 08:46:12.837978

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '81628ce16a9e'
down_revision = '3ba718bf39af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('laporan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('judul_laporan', sa.Text(), nullable=False),
    sa.Column('deskripsi', sa.Text(), nullable=False),
    sa.Column('estimasi', sa.String(length=20), nullable=False),
    sa.Column('kategori', sa.Enum('KERAMAIAN', 'TUMPUKAN_SAMPAH', name='kategori'), nullable=True),
    sa.Column('status_pengerjaan', sa.Enum('BARU', 'DIBACA', 'SELESAI', name='statuspengerjaan'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['User.id_user'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id_user', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('role', mysql.ENUM('ADMIN', 'USER', 'STAFF'), nullable=False),
    sa.Column('name_lengkap', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=35), nullable=False),
    sa.Column('no_telepon', mysql.VARCHAR(length=13), nullable=False),
    sa.Column('username', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id_user'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('email', ['email'], unique=True)

    op.drop_table('laporan')
    op.drop_table('User')
    # ### end Alembic commands ###
