"""initial commit

Revision ID: 83cf676c23d8
Revises: 
Create Date: 2025-04-06 00:26:09.560630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83cf676c23d8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'USER', 'STAFF', name='roleenum'), nullable=False),
    sa.Column('name_lengkap', sa.String(length=30), nullable=False),
    sa.Column('tanggal_lahir', sa.DateTime(), nullable=False),
    sa.Column('email', sa.String(length=35), nullable=False),
    sa.Column('no_telepon', sa.String(length=13), nullable=False),
    sa.Column('jenis_kelamin', sa.Enum('MALE', 'FEMALE', 'OTHER', name='genderenum'), nullable=False),
    sa.Column('username', sa.String(length=15), nullable=False),
    sa.Column('password', sa.String(length=25), nullable=False),
    sa.PrimaryKeyConstraint('id_user'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('User')
    # ### end Alembic commands ###
