"""fix(model) : fix enum status pengerjaan

Revision ID: 8d300dd9a151
Revises: 1786774023e4
Create Date: 2025-05-24 23:51:39.771071

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8d300dd9a151'
down_revision = '1786774023e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('laporan', schema=None) as batch_op:
        batch_op.alter_column('status_pengerjaan',
               existing_type=mysql.ENUM('BARU', 'DIBACA', 'SELESAI'),
               type_=sa.Enum('DITERIMA', 'DALAM_PENGERJAAN', 'SELESAI', name='statuspengerjaan'),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'User', ['id_user'], ['id_user'])

    with op.batch_alter_table('pengaduan', schema=None) as batch_op:
        batch_op.drop_constraint('pengaduan_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'User', ['id_user'], ['id_user'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pengaduan', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('pengaduan_ibfk_1', 'user', ['id_user'], ['id_user'])

    with op.batch_alter_table('laporan', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('status_pengerjaan',
               existing_type=sa.Enum('DITERIMA', 'DALAM_PENGERJAAN', 'SELESAI', name='statuspengerjaan'),
               type_=mysql.ENUM('BARU', 'DIBACA', 'SELESAI'),
               existing_nullable=True)

    # ### end Alembic commands ###
