"""feat(pengaduan) : new model and updated database

Revision ID: bc9ebe34d39a
Revises: 81628ce16a9e
Create Date: 2025-05-23 22:38:53.352426

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bc9ebe34d39a'
down_revision = '81628ce16a9e'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pengaduan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('katerogi_pengaduan', sa.Enum('KERAMAIAN', 'TUMPUKAN_SAMPAH', name='katerogipengaduan'), nullable=False),
    sa.Column('status_pengaduan', sa.Enum('BARU', 'DIBACA', 'SELESAI', name='statuspengaduan'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['User.id_user'], ),
    sa.PrimaryKeyConstraint('id')
    )

    with op.batch_alter_table('laporan', schema=None) as batch_op:
        batch_op.drop_constraint('laporan_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'User', ['id_user'], ['id_user'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('laporan', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('laporan_ibfk_1', 'user', ['id_user'], ['id_user'])

    op.drop_table('pengaduan')
    # ### end Alembic commands ###
